import Foundation

public struct CacheCandidate: Codable, Sendable {
    public let url: URL
    public let displayName: String
    public let sizeBytes: Int64
    public let lastModified: Date?
    public let reason: String
    public let confidence: Confidence

    public init(
        url: URL,
        displayName: String,
        sizeBytes: Int64,
        lastModified: Date?,
        reason: String,
        confidence: Confidence
    ) {
        self.url = url
        self.displayName = displayName
        self.sizeBytes = sizeBytes
        self.lastModified = lastModified
        self.reason = reason
        self.confidence = confidence
    }
}

/// Finds regenerable cache directories that are safe to move to the Trash.
///
/// Scope (per project decision): conservative app caches plus developer tool
/// caches. Everything reported here is recreated automatically by the owning
/// tool, and removal stays Trash-only so it is always reversible.
public struct CacheAnalyzer {
    private let fileManager: FileManager
    private let home: URL

    public init(fileManager: FileManager = .default, homeDirectory: URL? = nil) {
        self.fileManager = fileManager
        self.home = homeDirectory ?? fileManager.homeDirectoryForCurrentUser
    }

    public func findCaches(minimumSize: Int64 = 1_000_000) throws -> [CacheCandidate] {
        var candidates: [CacheCandidate] = []

        // Xcode DerivedData — presented as a single aggregate item, matching the
        // common "clear DerivedData" mental model.
        let derivedData = home.appendingPathComponent("Library/Developer/Xcode/DerivedData", isDirectory: true)
        if let candidate = candidate(
            at: derivedData,
            displayName: "Xcode DerivedData",
            reason: "Xcode build intermediates and indexes. Rebuilt automatically on the next build.",
            confidence: .high,
            minimumSize: minimumSize
        ) {
            candidates.append(candidate)
        }

        // Per-app caches: each immediate subfolder of ~/Library/Caches is one item.
        let userCaches = home.appendingPathComponent("Library/Caches", isDirectory: true)
        if let children = try? fileManager.contentsOfDirectory(
            at: userCaches,
            includingPropertiesForKeys: [.isDirectoryKey],
            options: [.skipsHiddenFiles]
        ) {
            for child in children {
                try Task.checkCancellation()
                guard (try? child.resourceValues(forKeys: [.isDirectoryKey]).isDirectory) == true else {
                    continue
                }
                if let candidate = candidate(
                    at: child,
                    displayName: Self.friendlyName(for: child.lastPathComponent),
                    reason: "Application cache. Regenerated by the app as needed.",
                    confidence: .high,
                    minimumSize: minimumSize
                ) {
                    candidates.append(candidate)
                }
            }
        }

        // Developer tool caches that live outside ~/Library/Caches.
        let devToolCaches: [(path: String, name: String)] = [
            (".npm/_cacache", "npm cache"),
            (".yarn/cache", "Yarn cache"),
            (".cache/yarn", "Yarn cache"),
            (".cache/pip", "pip cache"),
            (".gradle/caches", "Gradle cache")
        ]
        for tool in devToolCaches {
            try Task.checkCancellation()
            let url = home.appendingPathComponent(tool.path, isDirectory: true)
            if let candidate = candidate(
                at: url,
                displayName: tool.name,
                reason: "Developer tool download cache. Repopulated on demand.",
                confidence: .high,
                minimumSize: minimumSize
            ) {
                candidates.append(candidate)
            }
        }

        return candidates.sorted { $0.sizeBytes > $1.sizeBytes }
    }

    private func candidate(
        at url: URL,
        displayName: String,
        reason: String,
        confidence: Confidence,
        minimumSize: Int64
    ) -> CacheCandidate? {
        var isDirectory: ObjCBool = false
        guard fileManager.fileExists(atPath: url.path, isDirectory: &isDirectory), isDirectory.boolValue else {
            return nil
        }

        let size = directoryAllocatedSize(url)
        guard size >= minimumSize else {
            return nil
        }

        let lastModified = try? url.resourceValues(forKeys: [.contentModificationDateKey]).contentModificationDate
        return CacheCandidate(
            url: url,
            displayName: displayName,
            sizeBytes: size,
            lastModified: lastModified,
            reason: reason,
            confidence: confidence
        )
    }

    private func directoryAllocatedSize(_ url: URL) -> Int64 {
        guard let enumerator = fileManager.enumerator(
            at: url,
            includingPropertiesForKeys: [.isRegularFileKey, .totalFileAllocatedSizeKey, .fileSizeKey],
            options: []
        ) else {
            return 0
        }

        return enumerator.reduce(Int64(0)) { partial, item in
            guard let url = item as? URL,
                  let values = try? url.resourceValues(forKeys: [.isRegularFileKey, .totalFileAllocatedSizeKey, .fileSizeKey]),
                  values.isRegularFile == true else {
                return partial
            }
            return partial + Int64(values.totalFileAllocatedSize ?? values.fileSize ?? 0)
        }
    }

    /// Maps known cache folder names (often reverse-DNS bundle ids) to readable labels.
    static func friendlyName(for folderName: String) -> String {
        knownNames[folderName] ?? folderName
    }

    private static let knownNames: [String: String] = [
        "com.apple.dt.Xcode": "Xcode",
        "com.apple.Safari": "Safari",
        "com.apple.amp.itunesu": "iTunes U",
        "org.swift.swiftpm": "Swift Package Manager",
        "org.carthage.CarthageKit": "Carthage",
        "CocoaPods": "CocoaPods",
        "Homebrew": "Homebrew",
        "Yarn": "Yarn",
        "pip": "pip",
        "go-build": "Go build cache",
        "node-gyp": "node-gyp",
        "typescript": "TypeScript",
        "ms-playwright": "Playwright",
        "com.google.Chrome": "Google Chrome",
        "Google": "Google",
        "Firefox": "Firefox",
        "com.microsoft.VSCode": "Visual Studio Code"
    ]
}
